name: Build and Package NuGet

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Update version number in .csproj
      run: |
        VERSION=$(date +'%Y.%m.%d.%H%M')
        sed -i "s/<Version>.*<\/Version>/<Version>$VERSION<\/Version>/" RS2SwaggerAPI/RS2SwaggerAPI.csproj

    - name: Restore dependencies
      run: 
        dotnet restore RS2SwaggerAPI/RS2SwaggerAPI.csproj

    - name: Build
      run: 
        dotnet build RS2SwaggerAPI/RS2SwaggerAPI.csproj --configuration Release

    - name: Pack
      run: 
        dotnet pack --configuration Release --output ./nupkgs

    - name: Upload NuGet Packages
      uses: actions/upload-artifact@v3
      with:
        name: nuget-packages
        path: ./nupkgs/*.nupkg
        
    #- name: Push to NuGet
    #  run: dotnet nuget push ./nupkgs/*.nupkg --api-key ${{ secrets.NUGET }} --source https://api.nuget.org/v3/index.json
